version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot-mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: iot-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
      - DATABASE_PATH=/app/data/iot_dashboard.db
    volumes:
      - ./data:/app/data
    depends_on:
      - mosquitto
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: iot-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log: